#!/bin/sh

# Copyright 2014 Paul Jensen
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

CMD=$1

case $CMD in
    off)
	sudo sed -i.bak -e 's/^#\(.*distraction$\)/\1/' /etc/hosts
	;;
    ok)
	sudo sed -i.bak -e 's/^\([^#].*distraction$\)/#\1/' /etc/hosts
	;;
    add)
	sudo sh -c "echo '127.0.0.1 $2 www.$2 distraction' >> /etc/hosts"
	;;
    list)
	perl -ne 'print "$1\n" if /^#?127.0.0.1 (.*) distraction$/' < /etc/hosts
	;;
    *)
	echo "usage: $(basename $0) CMD"
	echo " distraction ok: allow distractions"
	echo " distraction off: disallow distractions"
	echo " distraction add domain (eg. twitter.com): add new site to distractables"
	echo " distraction list: list domains on distraction list"
esac
