#!/bin/sh

set -e

CMD=$1

case $CMD in
    off)
	sudo sed -i.bak -e 's/^#\(.*distraction$\)/\1/' /etc/hosts
	;;
    ok)
	sudo sed -i.bak -e 's/^\([^#].*distraction$\)/#\1/' /etc/hosts
	;;
    add)
	sudo sh -c "echo '127.0.0.1 $2 www.$2 distraction' >> /etc/hosts"
	;;
    list)
	perl -ne 'print "$1\n" if /^#?127.0.0.1 (.*) distraction$/' < /etc/hosts
	;;
    *)
	echo "usage: $(basename $0) CMD"
	echo " distraction ok: allow distractions"
	echo " distraction off: disallow distractions"
	echo " distraction add domain (eg. twitter.com): add new site to distractables"
	echo " distraction list: list domains on distraction list"
esac
